### ISSUE TITLE
libldap.so.2: undefined symbol

### ISSUE THREAD

**Issue by apoorvkh** [frostming/unearth#98]
**Describe the bug**

Hi, when I `pdm install` my `pdm.lock` file, I encounter the following error. I am able to resolve it by `conda install openldap`, but I'm wondering if there is a better solution (can we include ldap dependency or binaries in the unearth package)? Thank you!

```python
Traceback (most recent call last):
  File ".venv/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/pdm/installers/synchronizers.py", line 286, in
install_candidate
    self.manager.install(can)
  File ".venv/lib/python3.11/site-packages/pdm/installers/manager.py", line 34, in install
    dist_info = installer(str(prepared.build()), self.environment, prepared.direct_url())
                              ^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/pdm/models/candidates.py", line 403, in build
    self.obtain(allow_all=False)
  File ".venv/lib/python3.11/site-packages/pdm/models/candidates.py", line 458, in obtain
    self._unpack(validate_hashes=not allow_all)
  File ".venv/lib/python3.11/site-packages/pdm/models/candidates.py", line 472, in _unpack
    result = finder.download_and_unpack(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/unearth/finder.py", line 413, in download_and_unpack
    file = unpack_link(
           ^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/unearth/preparer.py", line 311, in unpack_link
    backend.fetch(link, location)
  File ".venv/lib/python3.11/site-packages/unearth/vcs/base.py", line 152, in fetch
    return self.fetch_new(location, url, rev, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".venv/lib/python3.11/site-packages/unearth/vcs/git.py", line 50, in fetch_new
    self.run_command(
  File ".venv/lib/python3.11/site-packages/unearth/vcs/base.py", line 78, in run_command
    raise UnpackError(e.output) from None
unearth.errors.UnpackError: /usr/libexec/git-core/git-remote-https: symbol lookup error: /lib64/libldap.so.2: undefined symbol: EVP_md2, version
```

**System:**

- `unearth` version: 0.14.0
- Python version: 3.11.7
- OS: Linux

**Comment by frostming** [comment]
It's not an issue of unearth, it is just invoking `git` to fetch the repository and `git` command fails due to the above reason.

**Comment by apoorvkh** [comment]
Understood, thanks!
